# Generated by Django 4.2.4 on 2023-08-03 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0002_remove_contactus_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactus",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="general.department",
            ),
        ),
    ]
